@extends('welcome.layouts.basic')
@section('title', 'Privacy Policy')

@section('stylesheets')
@endsection

@section('content')

	<div class="container w-full md:max-w-3xl mx-auto pt-20">
		<div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
			<!--Title-->
			<div class="">
				<h1 class="font-bold  break-normal text-main-900 pt-6 pb-2 text-3xl md:text-4xl">
					Privacy Policy
				</h1>
				<p class="text-sm md:text-base font-normal text-gray-600">
					Updated 06 February 2022
				</p>
			</div>

			<!--Page Content-->
			<div class="my-12 text-gray-600">
				<p class="py-6">
					This Privacy Policy describes how OceanSheet collects, uses and discloses information, and the choices that you have with respect to that information.
					<br><br>
					OceanSheet continuously works to make the Privacy Policy clear and understandable by dividing the Privacy Policy into the following sections.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Service
				</h1>
				<p class="py-6">
					The Service is the https://[www, app, blog, support ].oceansheet.com website, application, Google Sheets add-on, Microsoft Office add-in, and Microsoft Teams app operated by OceanSheet.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Personal Data
				</h1>
				<p class="py-6">
					Personal Data means data about a living individual who can be identified from this data (or from this and other information either in our possession or likely to come into our possession).
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Usage data
				</h1>
				<p class="py-6">
					Usage Data is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Cookies
				</h1>
				<p class="py-6">
					Cookies are small pieces of data stored on your device (computer or mobile device).
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Data controller
				</h1>
				<p class="py-6">
					Data Controller refers to the natural or legal person who (either alone, jointly, or in conjunction with other persons) determines the purposes for which and the manner in which any personal information is, or is to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of our User’s Personal Data. With regard to the Personal Data of any third party which may be included as content or metadata of any document uploaded by the User, we act as a Data Processor and the User acts as the Data Controller.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Data processors (or service providers)
				</h1>
				<p class="py-6">
					Data processor (or service provider) means any natural or legal person who processes data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Data subject
				</h1>
				<p class="py-6">
					Data Subject is any living individual who is the subject of Personal Data.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Requested account permissions
				</h1>
				<p class="py-6">
					Some permissions to your account are required for the product to operate. The Service will ask for permissions to access some specific scopes of your Google, or Microsoft, or Dropbox account. The permissions granted are used exclusively for the operation of the product limited to the services offered.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Information collection and use
				</h1>
				<p class="py-6">
					We collect several different types of information for various purposes to provide and improve our Service to you. The Service shall not transfer or share the data with third parties without your prior express consent. Furthermore, the Service shall rectify any inexact or incomplete data and shall eliminate it when it ceases to be necessary or pertinent for its purpose.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Usage data
				</h1>
				<p class="py-6">
					We may also collect information on how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Tracking cookies data
				</h1>
				<p class="py-6">
					We use cookies and similar tracking technologies to track activity on our Service and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our Service. Examples of Cookies we use: Session Cookies to operate our Service; Preference Cookies to remember your preferences and various settings; Security Cookies for security purposes. For more information about Cookies, please read our <router-link class="underline" :to="{ name: 'cookies.policy' }">  Cookies Policy </router-link>.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Legal basis for processing personal data under the General Data Protection Regulation (GDPR)
				</h1>
				<p class="py-6">
					If you are from the European Economic Area (EEA), the legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
					<br><br>
					OceanSheet may process your Personal Data because: We need to perform a contract with you; You have given us permission to do so; The processing is in our legitimate interests and it’s not overridden by your rights; For payment processing purposes; To comply with the law.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Retention of data
				</h1>
				<p class="py-6">
					OceanSheet will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy and for the duration applicable by law. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
					<br><br>
					OceanSheet will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Transfer of data
				</h1>
				<p class="py-6">
					Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction, where the data protection laws may differ from those of your jurisdiction. The persons in charge of data processing may be located outside the European Union. Others may include third parties necessary for the fulfillment of legal duties.
					<br><br>
					If you are located outside Hungary or the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to Hungary and the United States and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
					<br><br>
					OceanSheet will take all reasonable steps necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and that no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place regarding the security of your data and other personal information.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Security of data
				</h1>
				<p class="py-6">
					The security of your data is important to us and we don’t store any data contained in your files in our database, with the exception of the data in the header row (row 1) of all spreadsheet tabs. The rest of the data in your files never leaves your file storage (such as Google Drive, Dropbox, OneDrive, or SharePoint), and therefore inherits the entire security structure from your online file storage to ensure that it remains in your chosen environment. Furthermore, all interactions between your file storage account and our Service occur over a secure HTTPS connection. For more information on OceanSheet's security practices.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					“Do not track” signals
				</h1>
				<p class="py-6">
					We do not support Do Not Track (“DNT”). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Your data protection rights under General Data Protection Regulation (GDPR)
				</h1>
				<p class="py-6">
					If you are a resident of the European Economic Area (EEA), you have certain data protection rights. OceanSheet aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us at privacy@oceansheet.com.
					<br><br>
					In certain circumstances, you have the following data protection rights: The right to access, update or to delete the information we have on you: Where possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us at privacy@oceansheet.com to assist you. The right of rectification: You have the right to have your information rectified if that information is inaccurate or incomplete. The right to object: You have the right to object to our processing of your Personal Data. The right of restriction: You have the right to request that we restrict the processing of your personal information. The right to data portability: You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format. The right to withdraw consent: You also have the right to withdraw your consent at any time where OceanSheet relied on your consent to process your personal information. Please note that we may ask you to verify your identity before responding to such requests. You may exercise your rights by contacting us at privacy@oceansheet.com expressing your appropriate identification details and the specific right you wish to exercise.
					<br><br>
					Our policy on emails consists of sending only the messages you have asked to receive. If you do not wish to receive messages via email we will offer you the option of exercising your right to renounce receiving such messages. You also have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact our Data Protection Officer (privacy@oceansheet.com) or your local data protection authority in the European Economic Area (EEA).
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Service providers
				</h1>
				<p class="py-6">
					We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), to provide the Service on our behalf, to perform Service-related services (including resellers) or to assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Analytics
				</h1>
				<p class="py-6">
					We may use third-party Service Providers to monitor and analyze the use of our Service.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Behavioral remarketing
				</h1>
				<p class="py-6">
					OceanSheet uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Payments
				</h1>
				<p class="py-6">
					We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information. The payment processors we work with are:
					<h1 class="py-2 text-2xl text-gray-800 underline">
						Stripe
					</h1>
					Their Privacy Policy can be viewed at https://stripe.com/us/privacy.
					<br><br>
					<h1 class="py-2 text-2xl text-gray-800 underline">
						PayPal
					</h1>
					Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full.
					<br><br>
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Links to other sites
				</h1>
				<p class="py-6">
					Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.
					<br><br>
					We have no control over and assume no responsibility for the content, privacy policies, cookies policies or practices of any third party sites or services.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Children’s Privacy
				</h1>
				<p class="py-6">
					Our Service does not address anyone under the age of 18 (“Children”). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us at privacy@oceansheet.com. If we become aware that we have collected Personal Data from children without verification of parental consent, we will take steps to remove that information from our servers.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Rights of California Residents
				</h1>
				<p class="py-6">
					OceanSheet does not share or disclose your personal information to third-parties for the third-parties’ direct marketing purposes. Therefore, California’s “Shine the Light” law (California Civil Code § 1798.83) does not apply to OceanSheet
					<br><br>
					If you are a California resident, California law provides you with specific rights regarding your personal information, including the right to request that we disclose certain information to you about the collection and use of your personal information over the past 12 months; the right to request that we delete any of your personal information that we have collected from you, subject to certain exceptions; and the right to opt-out of the “sale” of your personal information, as defined by California law. To make such a request, contact us at privacy@oceansheet.com , by toll free phone +1 (833) 491-0163 , or by mail at OceanSheet, La Marina de València, Muelle de la Aduana s/n, Edificio Lanzadera, 46024 València, Valencia. Please note that we are only required to respond to two such requests per customer each year.
					<br><br>
					You also have the right not to be discriminated against if you exercise any of your rights under California privacy law.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Changes to this Privacy Policy
				</h1>
				<p class="py-6">
					We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
				</p>

				<h1 class="py-2 text-3xl text-gray-800">
					Contact us
				</h1>
				<p class="py-6">
					If you have any questions about this Privacy Policy, please contact us at privacy@oceansheet.com.
				</p>
			</div>
		</div>
	</div>

@endsection

@section('scripts')
@endsection